name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Debug Signing
        run: |
          # Генерируем дебажный ключ
          mkdir -p ~/.android
          keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug, O=Android, C=US"
          
          # Создаем файл свойств, который ожидает gradle на 41 строке
          # Файл создается в корне проекта
          echo "storeFile=/home/runner/.android/debug.keystore" > keystore.properties
          echo "storePassword=android" >> keystore.properties
          echo "keyAlias=androiddebugkey" >> keystore.properties
          echo "keyPassword=android" >> keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleEmulatorRelease

      - name: Get version
        id: get_version
        run: |
          msg=$(git log -1 --pretty=format:"%s")
          version=$(echo "${msg##* }" | tr -d '[:space:]')
          [[ -z "$version" ]] && version="v1.0.0"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Prepare symbols
        run: |
          mkdir -p artifact/mapping
          find app/build/outputs/native-debug-symbols -type f -exec cp {} artifact/ \; 2>/dev/null || true
          find app/build/outputs/mapping -type f -exec cp {} artifact/mapping/ \; 2>/dev/null || true
          if [ -d "artifact" ]; then
            cd artifact && zip -r ../symbols.zip .
          else
            touch ../symbols.zip
          fi

      - name: Draft GitHub Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.get_version.outputs.version }}
          prerelease: false
          draft: true
          files: |
            app/build/outputs/apk/emulator/release/*.apk
            symbols.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "JL-Mod_${{ steps.get_version.outputs.version }}"
          path: |
            app/build/outputs/apk/emulator/release/*.apk
            symbols.zip
