name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0 # Нужно для корректного лога git

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEY }}
          ENCODED_PROPS: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: |
          if [ -z "$ENCODED_PROPS" ]; then
            echo "Secrets not found, skipping decoding..."
          else
            echo "$ENCODED_KEYSTORE" | base64 -di > keystore.jks
            echo "$ENCODED_PROPS" | base64 -di > keystore.properties
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleEmulatorRelease

      - name: Get version
        id: get_version
        run: |
          # Берем последнее слово из коммита как версию или дефолт 'v1.0.0'
          msg=$(git log -1 --pretty=format:"%s")
          version=$(echo "${msg##* }" | tr -d '[:space:]')
          [[ -z "$version" ]] && version="v1.0.0"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Prepare symbols
        run: |
          mkdir -p artifact/mapping
          # Используем find, чтобы избежать ошибок "No such file or directory" при пустых папках
          find app/build/outputs/native-debug-symbols -type f -exec cp {} artifact/ \; 2>/dev/null || true
          find app/build/outputs/mapping -type f -exec cp {} artifact/mapping/ \; 2>/dev/null || true
          cd artifact && zip -r ../symbols.zip .

      - name: Draft GitHub Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.get_version.outputs.version }}
          prerelease: false
          draft: true
          files: |
            app/build/outputs/apk/emulator/release/*.apk
            symbols.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "JL-Mod_${{ steps.get_version.outputs.version }}"
          path: |
            app/build/outputs/apk/emulator/release/*.apk
            symbols.zip
